services:
  jellyfin:
    image: jellyfin/jellyfin:10.11
    container_name: jellyfin
    hostname: jellyfin

    user: "${PUID}:${PGID}"

    group_add:
      - "${RENDER_GID}"

    environment:
      TZ: "${TZ}"
      JELLYFIN_PublishedServerUrl: "http://${SERVER_IP}:8096"

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

    ports:
      - "${SERVER_IP}:8096:8096/tcp"
      - "${SERVER_IP}:7359:7359/udp"

    volumes:
      - type: bind
        source: ./.data/jellyfin/config
        target: /config

      - type: bind
        source: ./.data/jellyfin/cache
        target: /cache

      - type: bind
        source: /videos
        target: /media
        read_only: false

    restart: unless-stopped